### PR TITLE
update 67213

### PR DESCRIPTION
**Pull request by kewenchao**
racked-On: OAM-67213
Signed-off-by: Ge Yanfang yanfangx.ge@intel.com

### CODE REVIEW

**Review by sysctstage — APPROVED** [review]

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-changes on this PR.

FAILURE: CheckBug Bad comments/Bugs

For more information, see: /absp-staging/builders/opensource-autobuild/builds/498

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-approved on this PR.

FAILURE: CheckBug Bad comments/Bugs

For more information, see: /absp-staging/builders/opensource-autobuild/builds/499

**Review by sysctstage — COMMENTED** [review]
Autobuild started from pull-request-changes on this PR.

FAILURE: CheckBug Bad comments/Bugs

For more information, see: /absp-staging/builders/opensource-autobuild/builds/500

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/106

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckApprovals Some checks are failed. See the step results.html

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/114

**Review by sysctstage — APPROVED** [review]

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/115

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/116

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/117

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/118

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/121

**Review by shenya1x — COMMENTED** [review]
Failure when executing preintegration builder

FAILURE:CheckBug Bad comments/Bugs

More details, logs, and binaries: /absp-shenya1x_test/builders/opensource-preintegration/builds/129

**Pull request closed without merging**
